import { useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { Search, ShieldCheck } from "lucide-react";

export default function AdminAudit() {
  const { user } = useAuth(); const [search, setSearch] = useState(""); const [action, setAction] = useState("");
  const { data, isLoading } = trpc.admin.listAuditLogs.useQuery({ search, action: action || undefined, limit: 100 }, { enabled: user?.role === "admin" });
  if (!user || user.role !== "admin") return null;
  return <DashboardLayout><main className="mx-auto max-w-6xl space-y-6"><header><h1 className="text-2xl font-bold text-slate-900">Audit & Compliance</h1><p className="text-sm text-slate-500">Immutable history of privileged actions across the platform.</p></header><section className="flex flex-col gap-3 rounded-2xl border bg-white p-5 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search actions or reasons…" className="h-10 w-full rounded-xl border pl-9 text-sm" /></label><input value={action} onChange={e => setAction(e.target.value)} placeholder="Action e.g. user.banned" className="h-10 rounded-xl border px-3 text-sm" /></section><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center gap-2 border-b px-5 py-4"><ShieldCheck className="h-5 w-5 text-emerald-600" /><h2 className="font-semibold">Audit records</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="px-5 py-3">When</th><th className="px-5 py-3">Administrator</th><th className="px-5 py-3">Action</th><th className="px-5 py-3">Target</th><th className="px-5 py-3">Reason</th></tr></thead><tbody>{isLoading ? <tr><td colSpan={5} className="p-6">Loading…</td></tr> : data?.length ? data.map(log => <tr className="border-t" key={log.id}><td className="whitespace-nowrap px-5 py-3 text-slate-500">{new Date(log.createdAt).toLocaleString()}</td><td className="px-5 py-3">{log.adminName}</td><td className="px-5 py-3 font-medium">{log.action}</td><td className="px-5 py-3">{log.targetType} #{log.targetId}</td><td className="max-w-sm px-5 py-3 text-slate-600">{log.reason || "—"}</td></tr>) : <tr><td colSpan={5} className="p-8 text-center text-slate-500">No matching audit records.</td></tr>}</tbody></table></div></section></main></DashboardLayout>;
}
