import { useMemo, useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { useRoleGuard } from "@/hooks/useRoleGuard";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ClipboardCheck, Download, FileText, Save, Users } from "lucide-react";
import { toast } from "sonner";

export default function LecturerAssessments() {
  const { isAllowed } = useRoleGuard("lecturer"); const utils = trpc.useUtils();
  const [selected, setSelected] = useState<number | null>(null); const [grade, setGrade] = useState(""); const [feedback, setFeedback] = useState("");
  const [rubricScores, setRubricScores] = useState<Record<string, string>>({});
  const [templateName, setTemplateName] = useState(""); const [templateTitle, setTemplateTitle] = useState(""); const [templateDescription, setTemplateDescription] = useState("");
  const { data: queue, isLoading } = trpc.lecturer.assignments.reviewQueue.useQuery(undefined, { enabled: isAllowed });
  const { data: interventions } = trpc.lecturer.assignments.interventionStudents.useQuery(undefined, { enabled: isAllowed });
  const { data: missing } = trpc.lecturer.assignments.missingSubmissions.useQuery(undefined, { enabled: isAllowed });
  const { data: templates } = trpc.lecturer.assignments.templates.list.useQuery(undefined, { enabled: isAllowed });
  const gradeSubmission = trpc.lecturer.assignments.gradeSubmission.useMutation({ onSuccess: () => { toast.success("Grade and feedback sent to the student."); setSelected(null); setGrade(""); setFeedback(""); utils.lecturer.assignments.reviewQueue.invalidate(); } , onError: e => toast.error(e.message) });
  const createTemplate = trpc.lecturer.assignments.templates.create.useMutation({ onSuccess: () => { toast.success("Assessment template saved."); setTemplateName(""); setTemplateTitle(""); setTemplateDescription(""); utils.lecturer.assignments.templates.list.invalidate(); } });
  const pending = useMemo(() => queue?.filter(s => s.status !== "graded") ?? [], [queue]);
  const selectedSubmission = queue?.find((submission) => submission.id === selected);
  const selectedRubric = selectedSubmission?.rubric ?? [];
  if (!isAllowed) return null;
  const exportGrades = () => { const rows = [["Course", "Assignment", "Student", "Email", "Status", "Grade", "Submitted"], ...(queue ?? []).map(s => [s.courseId, s.assignmentTitle, s.studentName ?? "", s.studentEmail ?? "", s.status, s.grade ?? "", new Date(s.submittedAt).toLocaleString()])]; const blob = new Blob([rows.map(r => r.map(v => `"${String(v).replaceAll('"', '""')}"`).join(",")).join("\n")], { type: "text/csv" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "assessment-grades.csv"; a.click(); URL.revokeObjectURL(url); };
  return <DashboardLayout><main className="mx-auto max-w-6xl space-y-6"><header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-bold text-slate-900">Assessment & Feedback Center</h1><p className="text-sm text-slate-500">Review submissions, return feedback, and identify students who need support.</p></div><button onClick={exportGrades} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold hover:bg-slate-50"><Download className="h-4 w-4" />Export grades CSV</button></header>
    <section className="grid gap-4 sm:grid-cols-4"><Metric icon={<ClipboardCheck />} label="Awaiting review" value={pending.length} tone="amber" /><Metric icon={<FileText />} label="All submissions" value={queue?.length ?? 0} tone="indigo" /><Metric icon={<AlertTriangle />} label="Need intervention" value={interventions?.length ?? 0} tone="red" /><Metric icon={<Users />} label="Missing submissions" value={missing?.length ?? 0} tone="red" /></section>
    <section className="grid gap-6 xl:grid-cols-[1.5fr_0.8fr]"><div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="font-semibold">Submission review queue</h2><p className="text-xs text-slate-500">Late and ungraded submissions are ready for marking.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="px-5 py-3">Student</th><th className="px-5 py-3">Assignment</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Submitted</th><th /></tr></thead><tbody>{isLoading ? <tr><td colSpan={5} className="p-6">Loading…</td></tr> : queue?.length ? queue.map(s => <tr key={s.id} className="border-t"><td className="px-5 py-3"><b>{s.studentName}</b><br/><span className="text-xs text-slate-500">{s.studentEmail}</span></td><td className="px-5 py-3">{s.assignmentTitle}{s.fileUrl && <a className="ml-2 text-xs text-indigo-600 underline" href={s.fileUrl} target="_blank">File</a>}</td><td className="px-5 py-3"><Status value={s.status} late={!!s.dueDate && new Date(s.submittedAt) > new Date(s.dueDate)} /></td><td className="px-5 py-3 text-slate-500">{new Date(s.submittedAt).toLocaleDateString()}</td><td className="px-5 py-3"><button onClick={() => { setSelected(s.id); setGrade(s.grade ?? ""); setFeedback(s.feedback ?? ""); }} className="rounded-lg border px-3 py-1.5 text-indigo-700 hover:bg-indigo-50">{s.status === "graded" ? "Edit" : "Grade"}</button></td></tr>) : <tr><td colSpan={5} className="p-8 text-center text-slate-500">No submissions yet.</td></tr>}</tbody></table></div></div>
      <div className="space-y-6"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-3 flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-red-500" /><h2 className="font-semibold">Students needing intervention</h2></div><div className="max-h-72 divide-y overflow-auto">{interventions?.length ? interventions.map(s => <div className="py-3" key={s.studentId}><p className="font-medium">{s.name}</p><p className="text-xs text-slate-500">Quiz average {Math.round(s.averageScore)}% · {s.lateSubmissions} late · {s.lastActivity ? `active ${new Date(s.lastActivity).toLocaleDateString()}` : "no activity"}</p></div>) : <p className="py-4 text-sm text-slate-500">No intervention signals.</p>}</div></section><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Overdue and missing</h2><div className="mt-2 max-h-44 divide-y overflow-auto">{missing?.length ? missing.map(item => <div key={`${item.assignmentId}-${item.studentId}`} className="py-2 text-sm"><b>{item.studentName}</b><p className="text-xs text-red-600">Missing: {item.assignmentTitle}</p></div>) : <p className="py-3 text-sm text-slate-500">No overdue submissions missing.</p>}</div></section>
      <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-3 flex items-center gap-2"><Save className="h-5 w-5 text-emerald-600" /><h2 className="font-semibold">Reusable assessment templates</h2></div><div className="space-y-2"><input value={templateName} onChange={e => setTemplateName(e.target.value)} placeholder="Template name" className="h-9 w-full rounded-lg border px-3 text-sm" /><input value={templateTitle} onChange={e => setTemplateTitle(e.target.value)} placeholder="Assignment title" className="h-9 w-full rounded-lg border px-3 text-sm" /><textarea value={templateDescription} onChange={e => setTemplateDescription(e.target.value)} placeholder="Brief / marking instructions" className="min-h-20 w-full rounded-lg border p-3 text-sm" /><button disabled={!templateName || !templateTitle || createTemplate.isPending} onClick={() => createTemplate.mutate({ name: templateName, title: templateTitle, description: templateDescription || undefined })} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Save template</button></div><div className="mt-4 divide-y">{templates?.map(t => <div key={t.id} className="py-2 text-sm"><b>{t.name}</b><span className="ml-2 text-slate-500">{t.title}</span></div>)}</div></section></div></section>
    {selected !== null && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form onSubmit={e => { e.preventDefault(); const scores = selectedRubric.map(item => ({ criterion: item.criterion, score: Number(rubricScores[item.criterion] ?? 0) })); const calculated = selectedRubric.length ? scores.reduce((sum, item) => sum + item.score, 0) : Number(grade); if (!Number.isFinite(calculated)) return toast.error("Enter a valid grade."); if (scores.some((score, index) => score.score < 0 || score.score > selectedRubric[index].maxPoints)) return toast.error("A rubric score cannot exceed its criterion maximum."); gradeSubmission.mutate({ submissionId: selected, grade: calculated, feedback: feedback || undefined, rubricScores: selectedRubric.length ? scores : undefined }); }} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-lg font-bold">Grade submission</h2>{selectedRubric.length ? <div className="mt-4 space-y-3"><p className="text-sm font-medium">Rubric scores</p>{selectedRubric.map(item => <label className="flex items-center justify-between gap-4 text-sm" key={item.criterion}><span>{item.criterion} <span className="text-slate-400">/ {item.maxPoints}</span></span><input autoFocus type="number" min="0" max={item.maxPoints} value={rubricScores[item.criterion] ?? ""} onChange={e => setRubricScores(current => ({ ...current, [item.criterion]: e.target.value }))} className="h-9 w-24 rounded-lg border px-2" /></label>)}<p className="font-semibold text-indigo-700">Total: {selectedRubric.reduce((sum, item) => sum + Number(rubricScores[item.criterion] ?? 0), 0)} / {selectedRubric.reduce((sum, item) => sum + item.maxPoints, 0)}</p></div> : <label className="mt-4 block text-sm font-medium">Mark<input autoFocus type="number" min="0" value={grade} onChange={e => setGrade(e.target.value)} className="mt-1 h-10 w-full rounded-xl border px-3" /></label>}<label className="mt-4 block text-sm font-medium">Written feedback<textarea value={feedback} onChange={e => setFeedback(e.target.value)} className="mt-1 min-h-28 w-full rounded-xl border p-3" placeholder="Explain strengths and next steps…" /></label><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setSelected(null)} className="rounded-xl border px-4 py-2">Cancel</button><button disabled={gradeSubmission.isPending} className="rounded-xl bg-indigo-600 px-4 py-2 font-semibold text-white">{gradeSubmission.isPending ? "Saving…" : "Save & notify student"}</button></div></form></div>}
  </main></DashboardLayout>;
}
function Metric({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: number; tone: string }) { const colors: Record<string, string> = { amber: "text-amber-600", indigo: "text-indigo-600", red: "text-red-600" }; return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className={`flex gap-2 text-sm ${colors[tone]}`}>{icon}{label}</div><p className="mt-2 text-3xl font-bold">{value}</p></div>; }
function Status({ value, late }: { value: string; late: boolean }) { const text = value === "graded" ? "Graded" : late ? "Late" : "Submitted"; const color = value === "graded" ? "bg-emerald-50 text-emerald-700" : late ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"; return <span className={`rounded-full px-2 py-1 text-xs font-semibold ${color}`}>{text}</span>; }
